defaults: &defaults
  adapter: mysql2
  username: rails_app
  password: GTYHdse23B
  host: localhost

development:
  <<: *defaults
  database: midashboard_development

test:
  <<: *defaults
  database: midashboard_test

production:
  <<: *defaults
  database: midashboard

uat:
  <<: *defaults
  database: midashboard_uat
